// ==================================================
// File: src/config/admiralsData.ts
// ==================================================

import type { NationalRole, AdmiralTag } from '../types/game';
import type { Skill } from '../types/skill';

export interface BaseAdmiral {
    id: number;
    name: string;
    faction: 'empire' | 'alliance';
    stats: {
        command: number;
        operations: number;
        intelligence: number;
        mobility: number;
        attack: number;
        defense: number;
        tactics: number;
    };
    state: 'idle' | 'deployed' | 'wounded';
    deck: string[];
    // 特技系统
    skills: Skill[];
    // 核心档案数据
    rankName: string;
    flagshipName: string;
    imageId: string;
    // 阶段三：国家职务
    role: NationalRole;
    assignedNodeId: number | null; // 担任防卫司令官时绑定的节点
    loyalty?: number;              // 忠诚度 (0-100)，默认 70
    /** @deprecated 使用 tags 替代。过渡期保留，新逻辑只读 tags。 */
    hiddenStats: {
        ambition: number;      // 野心 (0-100)
        righteousness: number;  // 义理 (0-100)
        compatibility: number;  // 相性 (0-100)
    };
    // === 新增：标签数组（替代 hiddenStats 的 AI 决策依据） ===
    tags: AdmiralTag[];
    // 位置与所属
    currentNodeId: number | null;
    assignedFleetId: number | null;
    // 伤病系统
    injury: {
        isInjured: boolean;
        severity: number;    // 0-100
        recoveryTicks: number;
    };
}

export interface Admiral extends BaseAdmiral {
    rank: number; // 纯数字军阶 (1-13)
    level: number;
    tacticalMerits: number;
    adminMerits: number;
    politicalWork: number; // 政治工作值 (0-10000)
    staffs: number[];
    flagshipId: string;
}

export const admiralsData: BaseAdmiral[] = [
  { id:0, name:'艾齐纳哈', faction:'empire', rankName:'中将', flagshipName:'维札尔', imageId:'9000', state:'idle', deck:[], skills:[], stats:{ command:77, operations:22, intelligence:64, mobility:60, attack:82, defense:82, tactics:3000 } ,
    hiddenStats: { ambition: 70, righteousness: 37, compatibility: 45 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'frontal_assault', 'ruthless'] },
  { id:1, name:'艾亨道夫', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9001', state:'idle', deck:[], skills:[], stats:{ command:62, operations:36, intelligence:11, mobility:71, attack:82, defense:67, tactics:500 } ,
    hiddenStats: { ambition: 64, righteousness: 38, compatibility: 52 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['aggressive', 'realist'] },
  { id:2, name:'阿姆斯道尔夫', faction:'empire', rankName:'少校', flagshipName:'', imageId:'9002', state:'idle', deck:[], skills:[], stats:{ command:24, operations:63, intelligence:76, mobility:58, attack:46, defense:53, tactics:500 } ,
    hiddenStats: { ambition: 54, righteousness: 39, compatibility: 59 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['aristocrat', 'aggressive', 'realist'] },
  { id:3, name:'亚特林肯', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9003', state:'idle', deck:[], skills:[], stats:{ command:37, operations:70, intelligence:66, mobility:47, attack:49, defense:48, tactics:500 } ,
    hiddenStats: { ambition: 68, righteousness: 40, compatibility: 66 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:4, name:'安森巴哈', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9004', state:'idle', deck:[], skills:[], stats:{ command:58, operations:92, intelligence:89, mobility:60, attack:63, defense:58, tactics:2000 } ,
    hiddenStats: { ambition: 70, righteousness: 41, compatibility: 73 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['militarist', 'strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:5, name:'华根赛尔', faction:'empire', rankName:'少将', flagshipName:'瓦连当', imageId:'9097', state:'idle', deck:[], skills:[], stats:{ command:69, operations:33, intelligence:20, mobility:65, attack:62, defense:59, tactics:500 } ,
    hiddenStats: { ambition: 76, righteousness: 42, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'high_eq', 'opportunist'] },
  { id:6, name:'维拉', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9098', state:'idle', deck:[], skills:[], stats:{ command:42, operations:71, intelligence:38, mobility:59, attack:48, defense:55, tactics:500 } ,
    hiddenStats: { ambition: 74, righteousness: 43, compatibility: 46 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'realist'] },
  { id:7, name:'艾伦博克', faction:'empire', rankName:'元帅', flagshipName:'', imageId:'9005', state:'idle', deck:[], skills:[], stats:{ command:50, operations:98, intelligence:92, mobility:61, attack:32, defense:24, tactics:1000 } ,
    hiddenStats: { ambition: 20, righteousness: 85, compatibility: 55 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'military_minister' as NationalRole, assignedNodeId: null, tags: ['royalist', 'administrator', 'cautious'] },
  { id:8, name:'艾尔拉赫', faction:'empire', rankName:'中将', flagshipName:'海登海姆', imageId:'9006', state:'idle', deck:[], skills:[], stats:{ command:62, operations:25, intelligence:23, mobility:62, attack:68, defense:42, tactics:1000 } ,
    hiddenStats: { ambition: 80, righteousness: 45, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'opportunist'] },
  { id:9, name:'欧根', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9008', state:'idle', deck:[], skills:[], stats:{ command:43, operations:72, intelligence:68, mobility:27, attack:33, defense:53, tactics:500 } ,
    hiddenStats: { ambition: 76, righteousness: 46, compatibility: 67 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'opportunist'] },
  { id:10, name:'奥贝斯坦', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9007', state:'idle', deck:[], skills:[], stats:{ command:52, operations:99, intelligence:98, mobility:18, attack:20, defense:21, tactics:500 } ,
    hiddenStats: { ambition: 30, righteousness: 80, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'ruthless', 'high_iq', 'strategist', 'intel_focus'] },
  { id:11, name:'奥夫雷沙', faction:'empire', rankName:'上将', flagshipName:'', imageId:'9009', state:'idle', deck:[], skills:[], stats:{ command:9, operations:4, intelligence:2, mobility:8, attack:4, defense:18, tactics:8000 } ,
    hiddenStats: { ambition: 80, righteousness: 48, compatibility: 81 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'high_eq', 'opportunist'] },
  { id:12, name:'欧拉', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9010', state:'idle', deck:[], skills:[], stats:{ command:60, operations:39, intelligence:19, mobility:70, attack:59, defense:56, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 49, compatibility: 47 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'opportunist'] },
  { id:13, name:'卡尔纳普', faction:'empire', rankName:'少将', flagshipName:'赫尔默德', imageId:'9011', state:'idle', deck:[], skills:[], stats:{ command:64, operations:23, intelligence:12, mobility:91, attack:80, defense:62, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 50, compatibility: 54 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:14, name:'奇斯里', faction:'empire', rankName:'中校', flagshipName:'', imageId:'9012', state:'idle', deck:[], skills:[], stats:{ command:6, operations:2, intelligence:24, mobility:10, attack:10, defense:14, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 51, compatibility: 61 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:15, name:'吉尔菲艾斯', faction:'empire', rankName:'中将', flagshipName:'巴尔巴洛沙', imageId:'9013', state:'idle', deck:[], skills:[], stats:{ command:98, operations:56, intelligence:64, mobility:72, attack:90, defense:86, tactics:3000 } ,
    hiddenStats: { ambition: 25, righteousness: 98, compatibility: 90 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['royalist', 'high_charisma', 'righteous', 'tactician'] },
  { id:16, name:'克那普斯坦', faction:'empire', rankName:'准将', flagshipName:'乌尔丰', imageId:'9015', state:'idle', deck:[], skills:[], stats:{ command:71, operations:46, intelligence:36, mobility:64, attack:65, defense:80, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 53, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'high_eq', 'realist'] },
  { id:17, name:'库典森', faction:'empire', rankName:'中尉', flagshipName:'', imageId:'9018', state:'idle', deck:[], skills:[], stats:{ command:25, operations:66, intelligence:56, mobility:51, attack:44, defense:51, tactics:500 } ,
    hiddenStats: { ambition: 42, righteousness: 54, compatibility: 82 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['high_eq', 'realist'] },
  { id:18, name:'克拉杰', faction:'empire', rankName:'元帅', flagshipName:'', imageId:'9016', state:'idle', deck:[], skills:[], stats:{ command:51, operations:94, intelligence:88, mobility:21, attack:26, defense:36, tactics:1000 } ,
    hiddenStats: { ambition: 20, righteousness: 80, compatibility: 50 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['royalist', 'strategist', 'logistics_focus', 'cautious', 'high_iq', 'righteous'] },
  { id:19, name:'克拉普夫', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9017', state:'idle', deck:[], skills:[], stats:{ command:43, operations:53, intelligence:39, mobility:13, attack:12, defense:20, tactics:4000 } ,
    hiddenStats: { ambition: 62, righteousness: 56, compatibility: 55 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:20, name:'古利兹', faction:'empire', rankName:'中尉', flagshipName:'', imageId:'9019', state:'idle', deck:[], skills:[], stats:{ command:26, operations:53, intelligence:40, mobility:62, attack:36, defense:29, tactics:500 } ,
    hiddenStats: { ambition: 48, righteousness: 57, compatibility: 62 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:21, name:'克里希', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9014', state:'idle', deck:[], skills:[], stats:{ command:24, operations:64, intelligence:42, mobility:46, attack:41, defense:52, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 58, compatibility: 69 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:22, name:'格留尼曼', faction:'empire', rankName:'少将', flagshipName:'菲克利安德', imageId:'9021', state:'idle', deck:[], skills:[], stats:{ command:70, operations:41, intelligence:31, mobility:64, attack:60, defense:58, tactics:500 } ,
    hiddenStats: { ambition: 76, righteousness: 59, compatibility: 76 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'high_eq', 'realist'] },
  { id:23, name:'格利鲁帕尔兹', faction:'empire', rankName:'准将', flagshipName:'艾斯特拉', imageId:'9020', state:'idle', deck:[], skills:[], stats:{ command:66, operations:45, intelligence:51, mobility:83, attack:67, defense:63, tactics:500 } ,
    hiddenStats: { ambition: 74, righteousness: 37, compatibility: 42 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'aggressive', 'realist'] },
  { id:24, name:'古鲁坚休提伦', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9022', state:'idle', deck:[], skills:[], stats:{ command:67, operations:28, intelligence:20, mobility:76, attack:55, defense:72, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 38, compatibility: 49 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'aggressive', 'opportunist'] },
  { id:25, name:'古雷沙', faction:'empire', rankName:'中校', flagshipName:'', imageId:'9023', state:'idle', deck:[], skills:[], stats:{ command:8, operations:7, intelligence:6, mobility:12, attack:8, defense:15, tactics:4000 } ,
    hiddenStats: { ambition: 70, righteousness: 39, compatibility: 56 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'aggressive', 'realist'] },
  { id:26, name:'格雷布纳', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9024', state:'idle', deck:[], skills:[], stats:{ command:44, operations:76, intelligence:84, mobility:50, attack:30, defense:26, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 40, compatibility: 63 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'strategist', 'intel_focus', 'opportunist'] },
  { id:27, name:'克罗第瓦鲁', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9025', state:'idle', deck:[], skills:[], stats:{ command:68, operations:29, intelligence:15, mobility:73, attack:53, defense:68, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 41, compatibility: 70 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'opportunist'] },
  { id:28, name:'克斯拉', faction:'empire', rankName:'中将', flagshipName:'佛尔瑟帝', imageId:'9026', state:'idle', deck:[], skills:[], stats:{ command:93, operations:75, intelligence:86, mobility:52, attack:73, defense:62, tactics:500 } ,
    hiddenStats: { ambition: 70, righteousness: 70, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'intel_focus', 'cautious', 'high_iq', 'realist'] },
  { id:29, name:'坎普', faction:'empire', rankName:'中将', flagshipName:'优兹黑姆', imageId:'9027', state:'idle', deck:[], skills:[], stats:{ command:90, operations:20, intelligence:36, mobility:84, attack:96, defense:78, tactics:3000 } ,
    hiddenStats: { ambition: 50, righteousness: 65, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'frontal_assault', 'aggressive'] },
  { id:30, name:'曹肯', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9028', state:'idle', deck:[], skills:[], stats:{ command:63, operations:37, intelligence:24, mobility:67, attack:52, defense:73, tactics:1000 } ,
    hiddenStats: { ambition: 80, righteousness: 44, compatibility: 50 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'opportunist'] },
  { id:31, name:'山德斯', faction:'empire', rankName:'上尉', flagshipName:'', imageId:'9029', state:'idle', deck:[], skills:[], stats:{ command:23, operations:62, intelligence:61, mobility:57, attack:45, defense:56, tactics:500 } ,
    hiddenStats: { ambition: 74, righteousness: 45, compatibility: 57 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'realist'] },
  { id:32, name:'夏伍汀', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9030', state:'idle', deck:[], skills:[], stats:{ command:31, operations:82, intelligence:68, mobility:22, attack:22, defense:30, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 46, compatibility: 64 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['administrator', 'logistics_focus', 'opportunist'] },
  { id:33, name:'胥夫特', faction:'empire', rankName:'上将', flagshipName:'', imageId:'9031', state:'idle', deck:[], skills:[], stats:{ command:5, operations:50, intelligence:5, mobility:5, attack:2, defense:2, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 47, compatibility: 71 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'opportunist'] },
  { id:34, name:'斯坦赫夫', faction:'empire', rankName:'元帅', flagshipName:'', imageId:'9034', state:'idle', deck:[], skills:[], stats:{ command:58, operations:93, intelligence:90, mobility:43, attack:47, defense:43, tactics:1000 } ,
    hiddenStats: { ambition: 25, righteousness: 75, compatibility: 55 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'high_command_chief' as NationalRole, assignedNodeId: null, tags: ['royalist', 'strategist', 'logistics_focus', 'high_iq'] },
  { id:35, name:'舒坦梅茨', faction:'empire', rankName:'准将', flagshipName:'冯凯尔', imageId:'9035', state:'idle', deck:[], skills:[], stats:{ command:71, operations:90, intelligence:95, mobility:66, attack:80, defense:82, tactics:3000 } ,
    hiddenStats: { ambition: 64, righteousness: 49, compatibility: 44 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:36, name:'斯特汀', faction:'empire', rankName:'上将', flagshipName:'', imageId:'9033', state:'idle', deck:[], skills:[], stats:{ command:38, operations:85, intelligence:55, mobility:27, attack:72, defense:56, tactics:500 } ,
    hiddenStats: { ambition: 78, righteousness: 50, compatibility: 51 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'realist'] },
  { id:37, name:'休特克豪简', faction:'empire', rankName:'上将', flagshipName:'', imageId:'9036', state:'idle', deck:[], skills:[], stats:{ command:73, operations:56, intelligence:28, mobility:48, attack:77, defense:70, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 51, compatibility: 58 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'defense_commander' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'realist'] },
  { id:38, name:'休特雷', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9037', state:'idle', deck:[], skills:[], stats:{ command:48, operations:95, intelligence:85, mobility:36, attack:42, defense:27, tactics:500 } ,
    hiddenStats: { ambition: 70, righteousness: 52, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:39, name:'舒奈德', faction:'empire', rankName:'少校', flagshipName:'', imageId:'9038', state:'idle', deck:[], skills:[], stats:{ command:14, operations:69, intelligence:65, mobility:57, attack:47, defense:62, tactics:500 } ,
    hiddenStats: { ambition: 60, righteousness: 53, compatibility: 72 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'diplomat', 'realist'] },
  { id:40, name:'舒马赫', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9032', state:'idle', deck:[], skills:[], stats:{ command:35, operations:74, intelligence:62, mobility:59, attack:58, defense:55, tactics:1000 } ,
    hiddenStats: { ambition: 70, righteousness: 54, compatibility: 79 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'diplomat', 'high_eq', 'realist'] },
  { id:41, name:'修姆德', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9039', state:'idle', deck:[], skills:[], stats:{ command:2, operations:42, intelligence:5, mobility:3, attack:1, defense:2, tactics:500 } ,
    hiddenStats: { ambition: 72, righteousness: 55, compatibility: 45 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:42, name:'休勒', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9040', state:'idle', deck:[], skills:[], stats:{ command:54, operations:31, intelligence:18, mobility:68, attack:51, defense:71, tactics:500 } ,
    hiddenStats: { ambition: 74, righteousness: 56, compatibility: 52 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:43, name:'锦兹', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9041', state:'idle', deck:[], skills:[], stats:{ command:72, operations:35, intelligence:31, mobility:89, attack:78, defense:77, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 57, compatibility: 59 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'firepower', 'realist'] },
  { id:44, name:'杰克特', faction:'empire', rankName:'上将', flagshipName:'', imageId:'9043', state:'idle', deck:[], skills:[], stats:{ command:72, operations:31, intelligence:24, mobility:61, attack:76, defense:79, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 58, compatibility: 66 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'firepower', 'realist'] },
  { id:45, name:'赛贝尔', faction:'empire', rankName:'少校', flagshipName:'', imageId:'9042', state:'idle', deck:[], skills:[], stats:{ command:28, operations:65, intelligence:72, mobility:40, attack:46, defense:35, tactics:500 } ,
    hiddenStats: { ambition: 72, righteousness: 59, compatibility: 73 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'diplomat', 'realist'] },
  { id:46, name:'宋年菲尔斯', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9044', state:'idle', deck:[], skills:[], stats:{ command:39, operations:77, intelligence:59, mobility:27, attack:45, defense:34, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 37, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'aggressive', 'high_eq', 'opportunist'] },
  { id:47, name:'宋巴尔特', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9045', state:'idle', deck:[], skills:[], stats:{ command:57, operations:32, intelligence:10, mobility:72, attack:50, defense:66, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 38, compatibility: 46 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'aggressive', 'opportunist'] },
  { id:48, name:'狄克尔', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9046', state:'idle', deck:[], skills:[], stats:{ command:40, operations:86, intelligence:71, mobility:53, attack:40, defense:57, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 39, compatibility: 53 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'administrator', 'logistics_focus', 'aggressive', 'opportunist'] },
  { id:49, name:'狄塔斯多夫', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9047', state:'idle', deck:[], skills:[], stats:{ command:27, operations:73, intelligence:47, mobility:42, attack:42, defense:37, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 40, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'opportunist'] },
  { id:50, name:'迪尔克先', faction:'empire', rankName:'中校', flagshipName:'', imageId:'9048', state:'idle', deck:[], skills:[], stats:{ command:32, operations:78, intelligence:70, mobility:58, attack:50, defense:34, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 41, compatibility: 67 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'opportunist'] },
  { id:51, name:'特奈杰', faction:'empire', rankName:'准将', flagshipName:'西奥德里克', imageId:'9049', state:'idle', deck:[], skills:[], stats:{ command:60, operations:40, intelligence:32, mobility:81, attack:77, defense:58, tactics:1000 } ,
    hiddenStats: { ambition: 62, righteousness: 42, compatibility: 74 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:52, name:'德瑞文滋', faction:'empire', rankName:'上尉', flagshipName:'', imageId:'9050', state:'idle', deck:[], skills:[], stats:{ command:23, operations:65, intelligence:44, mobility:55, attack:41, defense:52, tactics:500 } ,
    hiddenStats: { ambition: 48, righteousness: 43, compatibility: 81 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['high_eq', 'realist'] },
  { id:53, name:'德洛伊杰', faction:'empire', rankName:'少将', flagshipName:'库克林', imageId:'9051', state:'idle', deck:[], skills:[], stats:{ command:69, operations:27, intelligence:20, mobility:80, attack:78, defense:64, tactics:500 } ,
    hiddenStats: { ambition: 70, righteousness: 44, compatibility: 47 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'realist'] },
  { id:54, name:'奈西巴哈', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9052', state:'idle', deck:[], skills:[], stats:{ command:34, operations:84, intelligence:85, mobility:29, attack:27, defense:25, tactics:500 } ,
    hiddenStats: { ambition: 72, righteousness: 45, compatibility: 54 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:55, name:'诺多海姆', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9053', state:'idle', deck:[], skills:[], stats:{ command:30, operations:80, intelligence:53, mobility:23, attack:23, defense:33, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 46, compatibility: 61 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['administrator', 'logistics_focus', 'realist'] },
  { id:56, name:'拜耶尔蓝', faction:'empire', rankName:'少将', flagshipName:'纽伦堡', imageId:'9057', state:'idle', deck:[], skills:[], stats:{ command:74, operations:38, intelligence:80, mobility:90, attack:81, defense:60, tactics:500 } ,
    hiddenStats: { ambition: 55, righteousness: 65, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['tactician', 'intel_focus', 'realist'] },
  { id:57, name:'豪夫', faction:'empire', rankName:'中尉', flagshipName:'', imageId:'9054', state:'idle', deck:[], skills:[], stats:{ command:12, operations:51, intelligence:46, mobility:34, attack:37, defense:35, tactics:500 } ,
    hiddenStats: { ambition: 54, righteousness: 48, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['high_eq', 'realist'] },
  { id:58, name:'豪普特曼', faction:'empire', rankName:'少校', flagshipName:'', imageId:'9055', state:'idle', deck:[], skills:[], stats:{ command:1, operations:1, intelligence:97, mobility:4, attack:2, defense:17, tactics:500 } ,
    hiddenStats: { ambition: 64, righteousness: 49, compatibility: 82 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['diplomat', 'intel_focus', 'high_iq', 'high_eq'] },
  { id:59, name:'派特利肯', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9059', state:'idle', deck:[], skills:[], stats:{ command:59, operations:33, intelligence:11, mobility:75, attack:52, defense:61, tactics:500 } ,
    hiddenStats: { ambition: 78, righteousness: 50, compatibility: 48 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:60, name:'巴尔豪萨', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9058', state:'idle', deck:[], skills:[], stats:{ command:61, operations:21, intelligence:14, mobility:93, attack:83, defense:62, tactics:500 } ,
    hiddenStats: { ambition: 76, righteousness: 51, compatibility: 55 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:61, name:'哈尔巴休泰德', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9056', state:'idle', deck:[], skills:[], stats:{ command:70, operations:34, intelligence:18, mobility:92, attack:74, defense:75, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 52, compatibility: 62 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'realist'] },
  { id:62, name:'毕典菲尔特', faction:'empire', rankName:'中将', flagshipName:'王虎', imageId:'9061', state:'idle', deck:[], skills:[], stats:{ command:75, operations:22, intelligence:38, mobility:78, attack:100, defense:54, tactics:3000 } ,
    hiddenStats: { ambition: 60, righteousness: 55, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'frontal_assault', 'aggressive'] },
  { id:63, name:'皮罗', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9062', state:'idle', deck:[], skills:[], stats:{ command:73, operations:54, intelligence:58, mobility:66, attack:67, defense:81, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 54, compatibility: 76 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'high_eq', 'realist'] },
  { id:64, name:'希德斯哈姆', faction:'empire', rankName:'中将', flagshipName:'', imageId:'9060', state:'idle', deck:[], skills:[], stats:{ command:18, operations:6, intelligence:30, mobility:29, attack:56, defense:25, tactics:1000 } ,
    hiddenStats: { ambition: 80, righteousness: 55, compatibility: 42 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:65, name:'法伦海特', faction:'empire', rankName:'中将', flagshipName:'亚斯古里', imageId:'9064', state:'idle', deck:[], skills:[], stats:{ command:80, operations:27, intelligence:37, mobility:86, attack:94, defense:67, tactics:3000 } ,
    hiddenStats: { ambition: 50, righteousness: 60, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'mobile_raid', 'aggressive'] },
  { id:66, name:'菲尔纳', faction:'empire', rankName:'中校', flagshipName:'', imageId:'9065', state:'idle', deck:[], skills:[], stats:{ command:7, operations:3, intelligence:100, mobility:7, attack:3, defense:19, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 57, compatibility: 56 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'intel_focus', 'high_iq', 'realist'] },
  { id:67, name:'佛格', faction:'empire', rankName:'上将', flagshipName:'贝茨曼', imageId:'9066', state:'idle', deck:[], skills:[], stats:{ command:68, operations:31, intelligence:49, mobility:67, attack:55, defense:69, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 58, compatibility: 63 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:68, name:'布克斯提夫德', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9069', state:'idle', deck:[], skills:[], stats:{ command:33, operations:81, intelligence:74, mobility:24, attack:26, defense:28, tactics:500 } ,
    hiddenStats: { ambition: 62, righteousness: 59, compatibility: 70 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'realist'] },
  { id:69, name:'费赛尼亚', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9063', state:'idle', deck:[], skills:[], stats:{ command:66, operations:78, intelligence:83, mobility:32, attack:23, defense:42, tactics:500 } ,
    hiddenStats: { ambition: 68, righteousness: 37, compatibility: 77 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['strategist', 'intel_focus', 'aggressive', 'high_eq', 'realist'] },
  { id:70, name:'布拉斯契', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9070', state:'idle', deck:[], skills:[], stats:{ command:67, operations:62, intelligence:52, mobility:66, attack:75, defense:63, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 38, compatibility: 43 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['aggressive', 'realist'] },
  { id:71, name:'布朗胥百克', faction:'empire', rankName:'元帅', flagshipName:'柏林', imageId:'9071', state:'idle', deck:[], skills:[], stats:{ command:25, operations:9, intelligence:30, mobility:28, attack:48, defense:32, tactics:1000 } ,
    hiddenStats: { ambition: 40, righteousness: 30, compatibility: 40 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['aristocrat', 'opportunist'] },
  { id:72, name:'布尔达哈', faction:'empire', rankName:'中尉', flagshipName:'', imageId:'9068', state:'idle', deck:[], skills:[], stats:{ command:13, operations:55, intelligence:43, mobility:54, attack:39, defense:37, tactics:500 } ,
    hiddenStats: { ambition: 50, righteousness: 40, compatibility: 57 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:73, name:'菲列格尔', faction:'empire', rankName:'中将', flagshipName:'', imageId:'9067', state:'idle', deck:[], skills:[], stats:{ command:19, operations:8, intelligence:36, mobility:20, attack:42, defense:23, tactics:1000 } ,
    hiddenStats: { ambition: 80, righteousness: 41, compatibility: 64 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'opportunist'] },
  { id:74, name:'布连塔诺', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9072', state:'idle', deck:[], skills:[], stats:{ command:88, operations:59, intelligence:54, mobility:18, attack:21, defense:42, tactics:500 } ,
    hiddenStats: { ambition: 78, righteousness: 42, compatibility: 71 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'high_iq', 'opportunist'] },
  { id:75, name:'贝尔肯格林', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9073', state:'idle', deck:[], skills:[], stats:{ command:57, operations:88, intelligence:79, mobility:55, attack:34, defense:45, tactics:500 } ,
    hiddenStats: { ambition: 72, righteousness: 43, compatibility: 78 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'administrator', 'logistics_focus', 'high_eq', 'realist'] },
  { id:76, name:'何夫麦斯塔', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9074', state:'idle', deck:[], skills:[], stats:{ command:65, operations:24, intelligence:18, mobility:88, attack:85, defense:55, tactics:500 } ,
    hiddenStats: { ambition: 78, righteousness: 44, compatibility: 44 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'mobile_raid', 'opportunist'] },
  { id:77, name:'荷尔兹拜亚', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9075', state:'idle', deck:[], skills:[], stats:{ command:87, operations:58, intelligence:80, mobility:14, attack:21, defense:36, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 45, compatibility: 51 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'intel_focus', 'high_iq', 'opportunist'] },
  { id:78, name:'麦佛赫', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9077', state:'idle', deck:[], skills:[], stats:{ command:63, operations:30, intelligence:13, mobility:70, attack:51, defense:59, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 46, compatibility: 58 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'opportunist'] },
  { id:79, name:'玛林道夫', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9076', state:'idle', deck:[], skills:[], stats:{ command:50, operations:89, intelligence:41, mobility:1, attack:1, defense:3, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 47, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['administrator', 'logistics_focus', 'opportunist'] },
  { id:80, name:'米达麦亚', faction:'empire', rankName:'中将', flagshipName:'人狼', imageId:'9078', state:'idle', deck:[], skills:[], stats:{ command:94, operations:35, intelligence:73, mobility:100, attack:91, defense:84, tactics:3000 } ,
    hiddenStats: { ambition: 65, righteousness: 75, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'mobile_raid', 'high_iq', 'tactician'] },
  { id:81, name:'莱因哈特', faction:'empire', rankName:'元帅', flagshipName:'伯伦希尔', imageId:'9094', state:'idle', deck:[], skills:[], stats:{ command:100, operations:31, intelligence:93, mobility:70, attack:93, defense:95, tactics:3000 } ,
    hiddenStats: { ambition: 95, righteousness: 70, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'space_fleet_deputy' as NationalRole, assignedNodeId: null, tags: ['ambition_faction', 'high_charisma', 'high_iq', 'tactician', 'aggressive'] },
  { id:82, name:'谬肯贝尔加', faction:'empire', rankName:'元帅', flagshipName:'维尔赫米纳', imageId:'9079', state:'idle', deck:[], skills:[], stats:{ command:89, operations:30, intelligence:35, mobility:63, attack:58, defense:60, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 50, compatibility: 45 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'space_fleet_commander' as NationalRole, assignedNodeId: null, tags: ['aristocrat', 'cautious', 'counter_defense', 'administrator'] },
  { id:83, name:'缪拉', faction:'empire', rankName:'少将', flagshipName:'帕西法尔', imageId:'9080', state:'idle', deck:[], skills:[], stats:{ command:82, operations:25, intelligence:54, mobility:68, attack:70, defense:100, tactics:3000 } ,
    hiddenStats: { ambition: 45, righteousness: 80, compatibility: 85 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['royalist', 'tactician', 'counter_defense', 'cautious', 'high_eq', 'righteous'] },
  { id:84, name:'梅克林格', faction:'empire', rankName:'中将', flagshipName:'库瓦希尔', imageId:'9081', state:'idle', deck:[], skills:[], stats:{ command:64, operations:96, intelligence:92, mobility:60, attack:72, defense:60, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 52, compatibility: 59 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'logistics_focus', 'high_iq', 'strategist'] },
  { id:85, name:'梅尔卡兹', faction:'empire', rankName:'上将', flagshipName:'诺德林根/西瓦', imageId:'9082', state:'idle', deck:[], skills:[], stats:{ command:86, operations:33, intelligence:63, mobility:77, attack:92, defense:98, tactics:3000 } ,
    hiddenStats: { ambition: 40, righteousness: 85, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['royalist', 'counter_defense', 'righteous', 'tactician'] },
  { id:86, name:'摩特', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9083', state:'idle', deck:[], skills:[], stats:{ command:86, operations:60, intelligence:60, mobility:16, attack:35, defense:50, tactics:1000 } ,
    hiddenStats: { ambition: 68, righteousness: 54, compatibility: 73 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'diplomat', 'high_iq', 'realist'] },
  { id:87, name:'莱博尔', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9084', state:'idle', deck:[], skills:[], stats:{ command:34, operations:83, intelligence:81, mobility:24, attack:24, defense:27, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 55, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'high_eq', 'realist'] },
  { id:88, name:'兰斯贝尔克', faction:'empire', rankName:'中将', flagshipName:'', imageId:'9085', state:'idle', deck:[], skills:[], stats:{ command:48, operations:22, intelligence:32, mobility:2, attack:5, defense:13, tactics:1000 } ,
    hiddenStats: { ambition: 76, righteousness: 56, compatibility: 46 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:89, name:'立典亥姆', faction:'empire', rankName:'元帅', flagshipName:'奥斯特马克', imageId:'9086', state:'idle', deck:[], skills:[], stats:{ command:20, operations:10, intelligence:24, mobility:19, attack:50, defense:26, tactics:1000 } ,
    hiddenStats: { ambition: 20, righteousness: 25, compatibility: 30 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['aristocrat', 'aggressive', 'ruthless', 'realist'] },
  { id:90, name:'立典拉德', faction:'empire', rankName:'宰相', flagshipName:'', imageId:'9087', state:'idle', deck:[], skills:[], stats:{ command:56, operations:100, intelligence:82, mobility:6, attack:4, defense:16, tactics:1000 } ,
    hiddenStats: { ambition: 60, righteousness: 20, compatibility: 25 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'prime_minister' as NationalRole, assignedNodeId: null, tags: ['strategist', 'logistics_focus', 'aggressive', 'ruthless', 'realist'] },
  { id:91, name:'流肯', faction:'empire', rankName:'少校', flagshipName:'', imageId:'9088', state:'idle', deck:[], skills:[], stats:{ command:10, operations:52, intelligence:33, mobility:38, attack:32, defense:38, tactics:500 } ,
    hiddenStats: { ambition: 62, righteousness: 59, compatibility: 67 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:92, name:'鲁兹', faction:'empire', rankName:'中将', flagshipName:'史奇尔尼尔', imageId:'9089', state:'idle', deck:[], skills:[], stats:{ command:81, operations:23, intelligence:48, mobility:86, attack:88, defense:85, tactics:3000 } ,
    hiddenStats: { ambition: 55, righteousness: 70, compatibility: 70 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['tactician', 'mobile_raid', 'firepower', 'realist'] },
  { id:93, name:'鲁比兹', faction:'empire', rankName:'中尉', flagshipName:'', imageId:'9090', state:'idle', deck:[], skills:[], stats:{ command:11, operations:57, intelligence:37, mobility:44, attack:38, defense:31, tactics:500 } ,
    hiddenStats: { ambition: 58, righteousness: 38, compatibility: 81 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['aristocrat', 'aggressive', 'high_eq', 'realist'] },
  { id:94, name:'列肯道夫', faction:'empire', rankName:'中尉', flagshipName:'', imageId:'9091', state:'idle', deck:[], skills:[], stats:{ command:15, operations:58, intelligence:50, mobility:49, attack:40, defense:41, tactics:500 } ,
    hiddenStats: { ambition: 60, righteousness: 39, compatibility: 47 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['aggressive', 'realist'] },
  { id:95, name:'列佛尔特', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9183', state:'idle', deck:[], skills:[], stats:{ command:36, operations:87, intelligence:87, mobility:30, attack:22, defense:22, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 40, compatibility: 54 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'strategist', 'logistics_focus', 'high_iq', 'opportunist'] },
  { id:96, name:'雷姆拉', faction:'empire', rankName:'中校', flagshipName:'', imageId:'9092', state:'idle', deck:[], skills:[], stats:{ command:35, operations:54, intelligence:50, mobility:15, attack:15, defense:21, tactics:3000 } ,
    hiddenStats: { ambition: 76, righteousness: 41, compatibility: 61 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'politician', 'opportunist'] },
  { id:97, name:'连内肯普', faction:'empire', rankName:'中将', flagshipName:'高尔加·法尔姆尔', imageId:'9093', state:'idle', deck:[], skills:[], stats:{ command:85, operations:45, intelligence:52, mobility:62, attack:74, defense:84, tactics:2000 } ,
    hiddenStats: { ambition: 80, righteousness: 42, compatibility: 68 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'frontal_assault', 'ruthless'] },
  { id:98, name:'罗严塔尔', faction:'empire', rankName:'中将', flagshipName:'托利斯坦', imageId:'9095', state:'idle', deck:[], skills:[], stats:{ command:92, operations:56, intelligence:73, mobility:73, attack:82, defense:90, tactics:3000 } ,
    hiddenStats: { ambition: 85, righteousness: 60, compatibility: 50 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['ambition_faction', 'high_iq', 'tactician', 'aggressive'] },
  { id:99, name:'瓦列', faction:'empire', rankName:'中将', flagshipName:'火龙', imageId:'9096', state:'idle', deck:[], skills:[], stats:{ command:84, operations:30, intelligence:64, mobility:82, attack:86, defense:89, tactics:3000 } ,
    hiddenStats: { ambition: 50, righteousness: 75, compatibility: 70 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['militarist', 'counter_defense', 'righteous'] },
  { id:100, name:'亚典波罗', faction:'alliance', rankName:'上校', flagshipName:'特里古拉夫', imageId:'9101', state:'idle', deck:[], skills:[], stats:{ command:72, operations:34, intelligence:64, mobility:85, attack:89, defense:83, tactics:3000 } ,
    hiddenStats: { ambition: 50, righteousness: 70, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['democrat', 'diplomat', 'mobile_raid', 'firepower', 'high_eq', 'realist'] },
  { id:101, name:'阿普顿', faction:'alliance', rankName:'中将', flagshipName:'克利什那', imageId:'9102', state:'idle', deck:[], skills:[], stats:{ command:77, operations:35, intelligence:53, mobility:71, attack:80, defense:77, tactics:2000 } ,
    hiddenStats: { ambition: 80, righteousness: 56, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'frontal_assault'] },
  { id:102, name:'雅拉肯', faction:'alliance', rankName:'少将', flagshipName:'玛尔杜克', imageId:'9103', state:'idle', deck:[], skills:[], stats:{ command:75, operations:30, intelligence:36, mobility:77, attack:90, defense:65, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 57, compatibility: 72 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'mobile_raid', 'realist'] },
  { id:103, name:'亚尔·沙列姆', faction:'alliance', rankName:'中将', flagshipName:'帕拉梅德斯', imageId:'9104', state:'idle', deck:[], skills:[], stats:{ command:78, operations:28, intelligence:52, mobility:70, attack:85, defense:76, tactics:3000 } ,
    hiddenStats: { ambition: 72, righteousness: 58, compatibility: 79 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'firepower'] },
  { id:104, name:'华利蒙特', faction:'alliance', rankName:'少尉', flagshipName:'', imageId:'9162', state:'idle', deck:[], skills:[], stats:{ command:15, operations:62, intelligence:60, mobility:42, attack:50, defense:37, tactics:500 } ,
    hiddenStats: { ambition: 38, righteousness: 59, compatibility: 45 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:105, name:'贝欧拉', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9163', state:'idle', deck:[], skills:[], stats:{ command:10, operations:68, intelligence:20, mobility:3, attack:3, defense:15, tactics:500 } ,
    hiddenStats: { ambition: 64, righteousness: 60, compatibility: 52 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:106, name:'伍兰夫', faction:'alliance', rankName:'中将', flagshipName:'盘古', imageId:'9105', state:'idle', deck:[], skills:[], stats:{ command:84, operations:39, intelligence:57, mobility:76, attack:94, defense:75, tactics:3000 } ,
    hiddenStats: { ambition: 55, righteousness: 65, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'frontal_assault', 'aggressive'] },
  { id:107, name:'艾凡思', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9107', state:'idle', deck:[], skills:[], stats:{ command:41, operations:93, intelligence:24, mobility:11, attack:17, defense:21, tactics:500 } ,
    hiddenStats: { ambition: 68, righteousness: 62, compatibility: 66 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'realist'] },
  { id:108, name:'亚达', faction:'alliance', rankName:'少校', flagshipName:'', imageId:'9106', state:'idle', deck:[], skills:[], stats:{ command:23, operations:10, intelligence:21, mobility:58, attack:55, defense:42, tactics:500 } ,
    hiddenStats: { ambition: 62, righteousness: 63, compatibility: 73 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:109, name:'艾默森', faction:'alliance', rankName:'少校', flagshipName:'', imageId:'9108', state:'idle', deck:[], skills:[], stats:{ command:54, operations:35, intelligence:23, mobility:62, attack:57, defense:53, tactics:500 } ,
    hiddenStats: { ambition: 64, righteousness: 64, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'high_eq', 'realist'] },
  { id:110, name:'卡尔先', faction:'alliance', rankName:'少将', flagshipName:'狄奥梅狄司', imageId:'9109', state:'idle', deck:[], skills:[], stats:{ command:73, operations:37, intelligence:48, mobility:84, attack:93, defense:68, tactics:2000 } ,
    hiddenStats: { ambition: 80, righteousness: 65, compatibility: 46 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'mobile_raid', 'realist'] },
  { id:111, name:'卡介伦', faction:'alliance', rankName:'少将', flagshipName:'', imageId:'9110', state:'idle', deck:[], skills:[], stats:{ command:53, operations:100, intelligence:42, mobility:20, attack:20, defense:24, tactics:500 } ,
    hiddenStats: { ambition: 20, righteousness: 90, compatibility: 85 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['democrat', 'administrator', 'logistics_focus', 'cautious', 'high_eq', 'righteous'] },
  { id:112, name:'阮文绍', faction:'alliance', rankName:'少将', flagshipName:'茉莉亚', imageId:'9113', state:'idle', deck:[], skills:[], stats:{ command:65, operations:40, intelligence:40, mobility:80, attack:96, defense:62, tactics:2000 } ,
    hiddenStats: { ambition: 80, righteousness: 67, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'mobile_raid', 'realist'] },
  { id:113, name:'库布斯里', faction:'alliance', rankName:'中将', flagshipName:'艾亚斯', imageId:'9111', state:'idle', deck:[], skills:[], stats:{ command:87, operations:74, intelligence:65, mobility:69, attack:78, defense:81, tactics:2000 } ,
    hiddenStats: { ambition: 80, righteousness: 68, compatibility: 67 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'counter_defense', 'administrator'] },
  { id:114, name:'格林希尔', faction:'alliance', rankName:'上将', flagshipName:'', imageId:'9115', state:'idle', deck:[], skills:[], stats:{ command:81, operations:98, intelligence:85, mobility:46, attack:48, defense:60, tactics:500 } ,
    hiddenStats: { ambition: 40, righteousness: 85, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'joint_ops_deputy' as NationalRole, assignedNodeId: null, tags: ['democrat', 'strategist', 'logistics_focus', 'cautious', 'high_iq', 'high_eq'] },
  { id:115, name:'克鲁思齐', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9112', state:'idle', deck:[], skills:[], stats:{ command:59, operations:9, intelligence:73, mobility:13, attack:12, defense:10, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 47, compatibility: 81 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['diplomat', 'high_eq', 'opportunist'] },
  { id:116, name:'科库兰', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9119', state:'idle', deck:[], skills:[], stats:{ command:34, operations:91, intelligence:19, mobility:10, attack:10, defense:20, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 48, compatibility: 47 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['administrator', 'logistics_focus', 'opportunist'] },
  { id:117, name:'可那利', faction:'alliance', rankName:'少将', flagshipName:'', imageId:'9120', state:'idle', deck:[], skills:[], stats:{ command:40, operations:87, intelligence:72, mobility:47, attack:34, defense:38, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 49, compatibility: 54 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['administrator', 'logistics_focus', 'opportunist'] },
  { id:118, name:'高尼夫', faction:'alliance', rankName:'中将', flagshipName:'', imageId:'9116', state:'idle', deck:[], skills:[], stats:{ command:59, operations:91, intelligence:86, mobility:38, attack:29, defense:35, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 50, compatibility: 61 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:119, name:'I依凡高尼夫', faction:'alliance', rankName:'上尉', flagshipName:'', imageId:'9117', state:'idle', deck:[], skills:[], stats:{ command:7, operations:3, intelligence:11, mobility:34, attack:26, defense:17, tactics:500 } ,
    hiddenStats: { ambition: 70, righteousness: 51, compatibility: 68 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:120, name:'科尔德威', faction:'alliance', rankName:'少尉', flagshipName:'', imageId:'9118', state:'idle', deck:[], skills:[], stats:{ command:6, operations:3, intelligence:9, mobility:35, attack:25, defense:16, tactics:500 } ,
    hiddenStats: { ambition: 36, righteousness: 52, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['high_eq', 'realist'] },
  { id:121, name:'沙尼亚', faction:'alliance', rankName:'准将', flagshipName:'贝连那斯', imageId:'9121', state:'idle', deck:[], skills:[], stats:{ command:57, operations:35, intelligence:35, mobility:74, attack:87, defense:76, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 53, compatibility: 82 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'frontal_assault', 'firepower', 'high_eq', 'realist'] },
  { id:122, name:'先寇布', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9122', state:'idle', deck:[], skills:[], stats:{ command:20, operations:32, intelligence:18, mobility:34, attack:27, defense:33, tactics:8000 } ,
    hiddenStats: { ambition: 40, righteousness: 50, compatibility: 55 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:123, name:'席特尼', faction:'alliance', rankName:'元帅', flagshipName:'', imageId:'9123', state:'idle', deck:[], skills:[], stats:{ command:90, operations:58, intelligence:58, mobility:65, attack:65, defense:88, tactics:3000 } ,
    hiddenStats: { ambition: 55, righteousness: 60, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'joint_ops_chief' as NationalRole, assignedNodeId: null, tags: ['tactician', 'counter_defense', 'high_iq', 'realist'] },
  { id:124, name:'夏尔强', faction:'alliance', rankName:'少校', flagshipName:'', imageId:'9124', state:'idle', deck:[], skills:[], stats:{ command:52, operations:23, intelligence:22, mobility:63, attack:62, defense:51, tactics:1000 } ,
    hiddenStats: { ambition: 60, righteousness: 56, compatibility: 62 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:125, name:'史路兹卡利达', faction:'alliance', rankName:'少校', flagshipName:'', imageId:'9125', state:'idle', deck:[], skills:[], stats:{ command:39, operations:74, intelligence:66, mobility:63, attack:53, defense:54, tactics:500 } ,
    hiddenStats: { ambition: 62, righteousness: 57, compatibility: 69 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:126, name:'史托克斯', faction:'alliance', rankName:'少将', flagshipName:'', imageId:'9126', state:'idle', deck:[], skills:[], stats:{ command:70, operations:86, intelligence:71, mobility:44, attack:44, defense:57, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 58, compatibility: 76 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'high_eq', 'realist'] },
  { id:127, name:'陈', faction:'alliance', rankName:'少将', flagshipName:'', imageId:'9127', state:'idle', deck:[], skills:[], stats:{ command:76, operations:89, intelligence:83, mobility:45, attack:46, defense:58, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 59, compatibility: 42 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'realist'] },
  { id:128, name:'邱吾权', faction:'alliance', rankName:'中将', flagshipName:'', imageId:'9184', state:'idle', deck:[], skills:[], stats:{ command:68, operations:90, intelligence:84, mobility:43, attack:31, defense:80, tactics:1000 } ,
    hiddenStats: { ambition: 80, righteousness: 60, compatibility: 49 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'realist'] },
  { id:129, name:'德森', faction:'alliance', rankName:'上将', flagshipName:'', imageId:'9129', state:'idle', deck:[], skills:[], stats:{ command:60, operations:92, intelligence:74, mobility:32, attack:30, defense:36, tactics:1000 } ,
    hiddenStats: { ambition: 80, righteousness: 61, compatibility: 56 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'realist'] },
  { id:130, name:'托达', faction:'alliance', rankName:'上尉', flagshipName:'', imageId:'9128', state:'idle', deck:[], skills:[], stats:{ command:3, operations:65, intelligence:1, mobility:2, attack:1, defense:1, tactics:500 } ,
    hiddenStats: { ambition: 68, righteousness: 62, compatibility: 63 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:131, name:'尼尔逊', faction:'alliance', rankName:'中校', flagshipName:'', imageId:'9185', state:'idle', deck:[], skills:[], stats:{ command:30, operations:26, intelligence:22, mobility:60, attack:61, defense:55, tactics:500 } ,
    hiddenStats: { ambition: 78, righteousness: 63, compatibility: 70 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:132, name:'派特', faction:'alliance', rankName:'中将', flagshipName:'波罗库斯', imageId:'9131', state:'idle', deck:[], skills:[], stats:{ command:83, operations:56, intelligence:58, mobility:72, attack:82, defense:79, tactics:2000 } ,
    hiddenStats: { ambition: 50, righteousness: 70, compatibility: 70 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['democrat', 'tactician', 'firepower', 'cautious', 'realist'] },
  { id:133, name:'巴格达胥', faction:'alliance', rankName:'中校', flagshipName:'', imageId:'9130', state:'idle', deck:[], skills:[], stats:{ command:5, operations:8, intelligence:100, mobility:7, attack:15, defense:14, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 65, compatibility: 43 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'intel_focus', 'high_iq', 'realist'] },
  { id:134, name:'培特雷', faction:'alliance', rankName:'上将', flagshipName:'雷欧达', imageId:'9132', state:'idle', deck:[], skills:[], stats:{ command:75, operations:34, intelligence:47, mobility:61, attack:86, defense:66, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 66, compatibility: 50 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'frontal_assault', 'realist'] },
  { id:135, name:'帕特里契夫', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9133', state:'idle', deck:[], skills:[], stats:{ command:73, operations:88, intelligence:89, mobility:72, attack:58, defense:63, tactics:1000 } ,
    hiddenStats: { ambition: 35, righteousness: 80, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['democrat', 'strategist', 'logistics_focus', 'cautious', 'high_iq', 'high_eq'] },
  { id:136, name:'比克古', faction:'alliance', rankName:'中将', flagshipName:'利欧·格兰特', imageId:'9134', state:'idle', deck:[], skills:[], stats:{ command:89, operations:33, intelligence:61, mobility:67, attack:92, defense:90, tactics:3000 } ,
    hiddenStats: { ambition: 30, righteousness: 85, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'righteous', 'tactician'] },
  { id:137, name:'毕罗莱尼', faction:'alliance', rankName:'少将', flagshipName:'', imageId:'9135', state:'idle', deck:[], skills:[], stats:{ command:33, operations:85, intelligence:92, mobility:60, attack:52, defense:48, tactics:500 } ,
    hiddenStats: { ambition: 68, righteousness: 69, compatibility: 71 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:138, name:'法菲尔', faction:'alliance', rankName:'中校', flagshipName:'', imageId:'9136', state:'idle', deck:[], skills:[], stats:{ command:27, operations:79, intelligence:68, mobility:75, attack:54, defense:56, tactics:500 } ,
    hiddenStats: { ambition: 58, righteousness: 47, compatibility: 78 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['diplomat', 'high_eq', 'realist'] },
  { id:139, name:'费雪', faction:'alliance', rankName:'准将', flagshipName:'希瓦', imageId:'9138', state:'idle', deck:[], skills:[], stats:{ command:56, operations:41, intelligence:45, mobility:100, attack:72, defense:59, tactics:500 } ,
    hiddenStats: { ambition: 68, righteousness: 48, compatibility: 44 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:140, name:'菲尔兹', faction:'alliance', rankName:'中尉', flagshipName:'', imageId:'9137', state:'idle', deck:[], skills:[], stats:{ command:12, operations:9, intelligence:7, mobility:40, attack:9, defense:11, tactics:500 } ,
    hiddenStats: { ambition: 50, righteousness: 49, compatibility: 51 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:141, name:'霍克', faction:'alliance', rankName:'准将', flagshipName:'', imageId:'9139', state:'idle', deck:[], skills:[], stats:{ command:25, operations:94, intelligence:71, mobility:49, attack:33, defense:34, tactics:500 } ,
    hiddenStats: { ambition: 72, righteousness: 50, compatibility: 58 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'realist'] },
  { id:142, name:'布拉多乔', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9140', state:'idle', deck:[], skills:[], stats:{ command:26, operations:73, intelligence:63, mobility:66, attack:50, defense:45, tactics:500 } ,
    hiddenStats: { ambition: 70, righteousness: 51, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:143, name:'布鲁姆哈尔特', faction:'alliance', rankName:'中尉', flagshipName:'', imageId:'9141', state:'idle', deck:[], skills:[], stats:{ command:13, operations:8, intelligence:15, mobility:12, attack:16, defense:28, tactics:4000 } ,
    hiddenStats: { ambition: 56, righteousness: 52, compatibility: 72 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:144, name:'菲列特莉加', faction:'alliance', rankName:'中尉', flagshipName:'', imageId:'9114', state:'idle', deck:[], skills:[], stats:{ command:11, operations:75, intelligence:83, mobility:42, attack:32, defense:40, tactics:500 } ,
    hiddenStats: { ambition: 20, righteousness: 80, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['democrat', 'strategist', 'intel_focus', 'cautious', 'high_eq', 'righteous'] },
  { id:145, name:'布隆兹', faction:'alliance', rankName:'中将', flagshipName:'', imageId:'9142', state:'idle', deck:[], skills:[], stats:{ command:30, operations:84, intelligence:94, mobility:15, attack:18, defense:23, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 54, compatibility: 45 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'intel_minister' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:146, name:'贝伊', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9143', state:'idle', deck:[], skills:[], stats:{ command:50, operations:22, intelligence:78, mobility:12, attack:11, defense:12, tactics:500 } ,
    hiddenStats: { ambition: 78, righteousness: 55, compatibility: 52 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:147, name:'赫伍得', faction:'alliance', rankName:'中将', flagshipName:'', imageId:'9144', state:'idle', deck:[], skills:[], stats:{ command:79, operations:36, intelligence:55, mobility:71, attack:83, defense:78, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 56, compatibility: 59 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'firepower'] },
  { id:148, name:'波布兰', faction:'alliance', rankName:'中尉', flagshipName:'', imageId:'9146', state:'idle', deck:[], skills:[], stats:{ command:8, operations:5, intelligence:12, mobility:39, attack:28, defense:19, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 57, compatibility: 66 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:149, name:'波罗汀', faction:'alliance', rankName:'中将', flagshipName:'佩伦', imageId:'9145', state:'idle', deck:[], skills:[], stats:{ command:82, operations:28, intelligence:58, mobility:78, attack:91, defense:79, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 58, compatibility: 73 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'mobile_raid'] },
  { id:150, name:'马逊', faction:'alliance', rankName:'准尉', flagshipName:'', imageId:'9147', state:'idle', deck:[], skills:[], stats:{ command:1, operations:2, intelligence:1, mobility:2, attack:1, defense:2, tactics:500 } ,
    hiddenStats: { ambition: 66, righteousness: 59, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'high_eq', 'realist'] },
  { id:151, name:'马里涅汀', faction:'alliance', rankName:'准将', flagshipName:'鲁斯坦', imageId:'9148', state:'idle', deck:[], skills:[], stats:{ command:56, operations:48, intelligence:37, mobility:73, attack:77, defense:73, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 60, compatibility: 46 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:152, name:'马利诺', faction:'alliance', rankName:'上校', flagshipName:'姆夫维瑟', imageId:'9149', state:'idle', deck:[], skills:[], stats:{ command:59, operations:38, intelligence:38, mobility:76, attack:79, defense:81, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 61, compatibility: 53 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'firepower', 'realist'] },
  { id:153, name:'慕亚', faction:'alliance', rankName:'上将', flagshipName:'佩加蒙', imageId:'9151', state:'idle', deck:[], skills:[], stats:{ command:70, operations:31, intelligence:48, mobility:75, attack:88, defense:74, tactics:3000 } ,
    hiddenStats: { ambition: 74, righteousness: 62, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'mobile_raid', 'realist'] },
  { id:154, name:'姆莱', faction:'alliance', rankName:'准将', flagshipName:'', imageId:'9152', state:'idle', deck:[], skills:[], stats:{ command:58, operations:96, intelligence:88, mobility:45, attack:40, defense:72, tactics:1000 } ,
    hiddenStats: { ambition: 64, righteousness: 63, compatibility: 67 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'strategist', 'logistics_focus', 'high_iq', 'realist'] },
  { id:155, name:'莫顿', faction:'alliance', rankName:'少将', flagshipName:'阿奇利沃斯', imageId:'9153', state:'idle', deck:[], skills:[], stats:{ command:64, operations:45, intelligence:55, mobility:81, attack:80, defense:78, tactics:2000 } ,
    hiddenStats: { ambition: 70, righteousness: 64, compatibility: 74 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_staff' as NationalRole, assignedNodeId: null, tags: ['reformer', 'firepower', 'realist'] },
  { id:156, name:'杨威利', faction:'alliance', rankName:'少将', flagshipName:'休伯利安', imageId:'9154', state:'idle', deck:[], skills:[], stats:{ command:100, operations:16, intelligence:80, mobility:62, attack:95, defense:99, tactics:3000 } ,
    hiddenStats: { ambition: 25, righteousness: 98, compatibility: 95 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'high_iq', 'idealist', 'strategist', 'mobile_raid', 'cautious'] },
  { id:157, name:'敏兹', faction:'alliance', rankName:'中尉', flagshipName:'尤利西斯', imageId:'9150', state:'idle', deck:[], skills:[], stats:{ command:1, operations:4, intelligence:8, mobility:8, attack:8, defense:3, tactics:500 } ,
    hiddenStats: { ambition: 50, righteousness: 66, compatibility: 47 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:158, name:'拉欧', faction:'alliance', rankName:'中校', flagshipName:'', imageId:'9155', state:'idle', deck:[], skills:[], stats:{ command:51, operations:78, intelligence:67, mobility:62, attack:56, defense:52, tactics:500 } ,
    hiddenStats: { ambition: 64, righteousness: 67, compatibility: 54 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:159, name:'拉普', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9156', state:'idle', deck:[], skills:[], stats:{ command:74, operations:80, intelligence:70, mobility:74, attack:64, defense:64, tactics:1000 } ,
    hiddenStats: { ambition: 70, righteousness: 68, compatibility: 61 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'realist'] },
  { id:160, name:'林滋', faction:'alliance', rankName:'少校', flagshipName:'', imageId:'9157', state:'idle', deck:[], skills:[], stats:{ command:14, operations:20, intelligence:12, mobility:11, attack:13, defense:29, tactics:4000 } ,
    hiddenStats: { ambition: 64, righteousness: 69, compatibility: 68 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:161, name:'鲁格拉希', faction:'alliance', rankName:'中将', flagshipName:'雷欧达II', imageId:'9158', state:'idle', deck:[], skills:[], stats:{ command:72, operations:32, intelligence:56, mobility:69, attack:84, defense:80, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 47, compatibility: 75 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'counter_defense', 'cautious'] },
  { id:162, name:'路菲普', faction:'alliance', rankName:'中将', flagshipName:'库·赫林', imageId:'9159', state:'idle', deck:[], skills:[], stats:{ command:74, operations:23, intelligence:52, mobility:64, attack:81, defense:73, tactics:3000 } ,
    hiddenStats: { ambition: 80, righteousness: 48, compatibility: 82 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'firepower', 'cautious'] },
  { id:163, name:'洛克维尔', faction:'alliance', rankName:'上将', flagshipName:'', imageId:'9160', state:'idle', deck:[], skills:[], stats:{ command:71, operations:95, intelligence:76, mobility:44, attack:35, defense:50, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 49, compatibility: 48 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['administrator', 'logistics_focus', 'opportunist'] },
  { id:164, name:'罗波斯', faction:'alliance', rankName:'元帅', flagshipName:'艾亚斯', imageId:'9161', state:'idle', deck:[], skills:[], stats:{ command:86, operations:39, intelligence:55, mobility:68, attack:75, defense:82, tactics:3000 } ,
    hiddenStats: { ambition: 50, righteousness: 65, compatibility: 65 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'space_fleet_commander' as NationalRole, assignedNodeId: null, tags: ['democrat', 'cautious', 'counter_defense', 'administrator'] },
  { id:165, name:'同盟最高评议会', faction:'alliance', rankName:'议会', flagshipName:'', imageId:'9164', state:'idle', deck:[], skills:[], stats:{ command:80, operations:90, intelligence:10, mobility:1, attack:1, defense:5, tactics:1000 } ,
    hiddenStats: { ambition: 60, righteousness: 40, compatibility: 35 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'council' as NationalRole, assignedNodeId: null, tags: ['democrat', 'politician', 'realist'] },
  { id:166, name:'威迪', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9186', state:'idle', deck:[], skills:[], stats:{ command:25, operations:76, intelligence:67, mobility:46, attack:38, defense:33, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 52, compatibility: 69 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:167, name:'休特劳斯', faction:'empire', rankName:'少将', flagshipName:'', imageId:'9187', state:'idle', deck:[], skills:[], stats:{ command:30, operations:65, intelligence:93, mobility:20, attack:34, defense:35, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 43, compatibility: 66 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'strategist', 'intel_focus', 'high_iq', 'opportunist'] },
  { id:168, name:'萨姆', faction:'empire', rankName:'准将', flagshipName:'', imageId:'9188', state:'idle', deck:[], skills:[], stats:{ command:60, operations:45, intelligence:78, mobility:30, attack:35, defense:38, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 44, compatibility: 73 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['militarist', 'diplomat', 'opportunist'] },
  { id:169, name:'卡姆胡巴', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9192', state:'idle', deck:[], skills:[], stats:{ command:52, operations:42, intelligence:25, mobility:75, attack:70, defense:58, tactics:500 } ,
    hiddenStats: { ambition: 80, righteousness: 45, compatibility: 80 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['politician', 'high_eq', 'opportunist'] },
  { id:170, name:'修莱雅', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9193', state:'idle', deck:[], skills:[], stats:{ command:55, operations:38, intelligence:30, mobility:68, attack:65, defense:62, tactics:500 } ,
    hiddenStats: { ambition: 58, righteousness: 46, compatibility: 46 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:171, name:'谬森休特', faction:'empire', rankName:'上校', flagshipName:'', imageId:'9194', state:'idle', deck:[], skills:[], stats:{ command:25, operations:72, intelligence:62, mobility:65, attack:45, defense:40, tactics:500 } ,
    hiddenStats: { ambition: 60, righteousness: 47, compatibility: 53 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:172, name:'克莱巴', faction:'empire', rankName:'中校', flagshipName:'', imageId:'9195', state:'idle', deck:[], skills:[], stats:{ command:51, operations:43, intelligence:32, mobility:65, attack:72, defense:68, tactics:500 } ,
    hiddenStats: { ambition: 58, righteousness: 48, compatibility: 60 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:173, name:'拉杰尔', faction:'empire', rankName:'少校', flagshipName:'', imageId:'9196', state:'idle', deck:[], skills:[], stats:{ command:30, operations:61, intelligence:50, mobility:15, attack:22, defense:24, tactics:500 } ,
    hiddenStats: { ambition: 56, righteousness: 49, compatibility: 67 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:174, name:'林查', faction:'empire', rankName:'中尉', flagshipName:'', imageId:'9197', state:'idle', deck:[], skills:[], stats:{ command:35, operations:5, intelligence:24, mobility:6, attack:23, defense:25, tactics:4000 } ,
    hiddenStats: { ambition: 50, righteousness: 50, compatibility: 74 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['realist'] },
  { id:175, name:'邦斯格尔', faction:'alliance', rankName:'少将', flagshipName:'', imageId:'9198', state:'idle', deck:[], skills:[], stats:{ command:64, operations:97, intelligence:50, mobility:15, attack:32, defense:14, tactics:500 } ,
    hiddenStats: { ambition: 76, righteousness: 61, compatibility: 50 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'administrator', 'logistics_focus', 'realist'] },
  { id:176, name:'马斯喀尼', faction:'alliance', rankName:'准将', flagshipName:'', imageId:'9199', state:'idle', deck:[], skills:[], stats:{ command:45, operations:18, intelligence:15, mobility:66, attack:52, defense:55, tactics:1000 } ,
    hiddenStats: { ambition: 74, righteousness: 62, compatibility: 57 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:177, name:'戴休', faction:'alliance', rankName:'上校', flagshipName:'', imageId:'9200', state:'idle', deck:[], skills:[], stats:{ command:60, operations:20, intelligence:51, mobility:34, attack:45, defense:42, tactics:1000 } ,
    hiddenStats: { ambition: 72, righteousness: 63, compatibility: 64 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:178, name:'贾瓦夫', faction:'alliance', rankName:'中校', flagshipName:'', imageId:'9201', state:'idle', deck:[], skills:[], stats:{ command:35, operations:10, intelligence:32, mobility:12, attack:10, defense:11, tactics:500 } ,
    hiddenStats: { ambition: 70, righteousness: 64, compatibility: 71 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'realist'] },
  { id:179, name:'亚修', faction:'alliance', rankName:'上尉', flagshipName:'', imageId:'9202', state:'idle', deck:[], skills:[], stats:{ command:72, operations:13, intelligence:32, mobility:53, attack:30, defense:31, tactics:1000 } ,
    hiddenStats: { ambition: 64, righteousness: 65, compatibility: 78 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'tactician', 'high_eq', 'realist'] },
  { id:180, name:'克罗歇尔', faction:'alliance', rankName:'准尉', flagshipName:'', imageId:'9203', state:'idle', deck:[], skills:[], stats:{ command:1, operations:2, intelligence:2, mobility:9, attack:3, defense:4, tactics:500 } ,
    hiddenStats: { ambition: 64, righteousness: 65, compatibility: 78 },
    currentNodeId: null,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'none' as NationalRole, assignedNodeId: null, tags: ['reformer', 'high_eq', 'realist'] },
  // === 新增：佛瑞德李希四世（银河帝国皇帝） ===
  { id:181, name:'佛瑞德李希四世', faction:'empire', rankName:'皇帝', flagshipName:'', imageId:'9171', state:'idle', deck:[], skills:[],
    stats:{ command:5, operations:3, intelligence:25, mobility:3, attack:3, defense:5, tactics:100 } ,
    hiddenStats: { ambition: 5, righteousness: 20, compatibility: 40 },
    currentNodeId: 56,
    assignedFleetId: null,
    injury: { isInjured: false, severity: 0, recoveryTicks: 0 }, role: 'emperor' as NationalRole, assignedNodeId: null, tags: ['royalist', 'opportunist', 'realist'] },
];