// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadGameData() {
  return window['go']['main']['App']['LoadGameData']();
}

export function SaveGameData(arg1) {
  return window['go']['main']['App']['SaveGameData'](arg1);
}
