// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadGameData():Promise<string>;

export function SaveGameData(arg1:string):Promise<void>;
